package com.cbox.business.question.analysis.util;

import java.util.LinkedHashMap;
import java.util.Map;

public class WorkTransUtil {

    public static Map<String, Object> mapWorkDict;

    static {
        mapWorkDict = new LinkedHashMap<String, Object>();

        /* 基础的字典转义  */
        mapWorkDict.put("qyj", "企业家");
        mapWorkDict.put("zfgwy", "政府公务员");
        mapWorkDict.put("ls", "老师");
        mapWorkDict.put("ys", "医生");
        mapWorkDict.put("qybl", "企业白领");
        mapWorkDict.put("jsry", "技术人员/工程师");
        mapWorkDict.put("gjzsfz", "高级知识分子");
        mapWorkDict.put("qt", "其他");

        /* 针对国庆宅家调研的特殊转义  */
        mapWorkDict.put("医疗","医生");
        mapWorkDict.put("金融","企业白领");
        mapWorkDict.put("教育","老师");
        mapWorkDict.put("IT","技术人员/工程师");
        mapWorkDict.put("政府","政府公务员");
        mapWorkDict.put("经商","企业家");
        mapWorkDict.put("外贸","企业家");
        mapWorkDict.put("教师","老师");
        mapWorkDict.put("政府机关","政府公务员");
        mapWorkDict.put("金融保险","企业白领");
        mapWorkDict.put("灯光设计师","技术人员/工程师");
        mapWorkDict.put("平面设计","技术人员/工程师");
        mapWorkDict.put("医疗卫生","医生");
        mapWorkDict.put("公务员","政府公务员");
        mapWorkDict.put("单位","企业白领");
        mapWorkDict.put("应急救援","医生");
        mapWorkDict.put("税收","政府公务员");
        mapWorkDict.put("护士","医生");
        mapWorkDict.put("生产制造","技术人员/工程师");
        mapWorkDict.put("会计","企业白领");
        mapWorkDict.put("销售","企业白领");
        mapWorkDict.put("行政","企业白领");
        mapWorkDict.put("法律","高级知识分子");
        mapWorkDict.put("建筑","技术人员/工程师");
        mapWorkDict.put("人力资源","企业白领");
        mapWorkDict.put("设计师","高级知识分子");
        mapWorkDict.put("职员","企业白领");
        mapWorkDict.put("财会","企业白领");
        mapWorkDict.put("事业单位","企业白领");
        mapWorkDict.put("医务人员","医生");
        mapWorkDict.put("人事","企业白领");
        mapWorkDict.put("企业办公","企业白领");
        mapWorkDict.put("计算机","技术人员/工程师");
        mapWorkDict.put("律师","高级知识分子");
        mapWorkDict.put("管理","企业家");
        mapWorkDict.put("通信","技术人员/工程师");
        mapWorkDict.put("业务","企业白领");
        mapWorkDict.put("企业","企业家");
        mapWorkDict.put("财务","企业白领");
        mapWorkDict.put("公职","政府公务员");
        mapWorkDict.put("医疗","医生");
        mapWorkDict.put("售后","企业白领");
        mapWorkDict.put("医生","医生");
        mapWorkDict.put("轮胎制造业","技术人员/工程师");
        mapWorkDict.put("事编","企业白领");
        mapWorkDict.put("文员","企业白领");
        mapWorkDict.put("中介","企业白领");
        mapWorkDict.put("国企","企业白领");
        mapWorkDict.put("网络","技术人员/工程师");
        mapWorkDict.put("普通职工","企业白领");
        mapWorkDict.put("电力","技术人员/工程师");
        mapWorkDict.put("银行从业","企业白领");
        mapWorkDict.put("企业职工","企业白领");
        mapWorkDict.put("医师","医生");
        mapWorkDict.put("电子通信","技术人员/工程师");
        mapWorkDict.put("办事专员","企业白领");
        mapWorkDict.put("上班族","企业白领");
        mapWorkDict.put("职工","企业白领");
        mapWorkDict.put("创业","企业家");
        mapWorkDict.put("机械","技术人员/工程师");
        mapWorkDict.put("制造","技术人员/工程师");
        mapWorkDict.put("老板","企业家");
        mapWorkDict.put("机关单位","政府公务员");
        mapWorkDict.put("商人","企业家");
        mapWorkDict.put("幼教","老师");
        mapWorkDict.put("企事业单位","企业白领");
        mapWorkDict.put("电脑","技术人员/工程师");
        mapWorkDict.put("it行业","技术人员/工程师");
        mapWorkDict.put("金融业","企业白领");
        mapWorkDict.put("传媒","企业白领");
        mapWorkDict.put("员工","企业白领");
        mapWorkDict.put("建筑业","技术人员/工程师");
        mapWorkDict.put("主管","企业白领");
        mapWorkDict.put("民航","企业白领");
        mapWorkDict.put("公共部门","政府公务员");
        mapWorkDict.put("公司","企业白领");
        mapWorkDict.put("保险","企业白领");
        mapWorkDict.put("财务管理","企业白领");
        mapWorkDict.put("事业学位","企业白领");
        mapWorkDict.put("计算机信息技术","技术人员/工程师");
        mapWorkDict.put("软件","技术人员/工程师");
        mapWorkDict.put("物业公司","企业白领");
        mapWorkDict.put("老师","老师");
        mapWorkDict.put("建筑设计","技术人员/工程师");
        mapWorkDict.put("教育培训","老师");
        mapWorkDict.put("医护人员","医生");
        mapWorkDict.put("航空维修","技术人员/工程师");
        mapWorkDict.put("微电子专家","高级知识分子");
        mapWorkDict.put("物业","企业白领");
        mapWorkDict.put("法律服务","高级知识分子");
        mapWorkDict.put("银行","企业白领");
        mapWorkDict.put("科研","高级知识分子");
        mapWorkDict.put("司法警察","政府公务员");
        mapWorkDict.put("芯片制造","技术人员/工程师");
        mapWorkDict.put("公职人员","政府公务员");
        mapWorkDict.put("策划","企业白领");
        mapWorkDict.put("政府事业单位","政府公务员");
        mapWorkDict.put("教育行业","老师");
        mapWorkDict.put("软件研发","技术人员/工程师");
        mapWorkDict.put("机关事业单位","企业白领"); 
        mapWorkDict.put("技术管理","技术人员/工程师");
        mapWorkDict.put("造价工程师","技术人员/工程师");
        mapWorkDict.put("国际贸易","企业白领");
        mapWorkDict.put("市政","企业白领");
        mapWorkDict.put("信息安全","技术人员/工程师");
        mapWorkDict.put("信息技术","技术人员/工程师");
        mapWorkDict.put("高管","企业白领");
        mapWorkDict.put("技术人员","技术人员/工程师");
        mapWorkDict.put("公司职员","企业白领");
        mapWorkDict.put("党政机关","政府公务员");
        mapWorkDict.put("讲师","老师");
        mapWorkDict.put("上班","企业白领");
        mapWorkDict.put("数据分析","企业白领");
        mapWorkDict.put("企业行政管理","企业白领");
        mapWorkDict.put("化工行业","技术人员/工程师");
        mapWorkDict.put("国企职工","企业白领");
        mapWorkDict.put("企事业","企业白领");
        mapWorkDict.put("工薪阶层","企业白领");
        mapWorkDict.put("计算机软件开发","技术人员/工程师");
        mapWorkDict.put("工程机械","技术人员/工程师");
        mapWorkDict.put("医疗","医生");
        mapWorkDict.put("软件销售","企业白领");
        mapWorkDict.put("技术服务","技术人员/工程师");
        mapWorkDict.put("机械行业","技术人员/工程师");
        mapWorkDict.put("机械制造业","技术人员/工程师");
        mapWorkDict.put("医疗","医生");
        mapWorkDict.put("软件开发","技术人员/工程师");
        mapWorkDict.put("城市规划","技术人员/工程师");
        mapWorkDict.put("白领","企业白领");
        mapWorkDict.put("检测员","技术人员/工程师");
        mapWorkDict.put("工作人员","技术人员/工程师");
        mapWorkDict.put("小学教师","老师");
        mapWorkDict.put("医疗","医生");
        mapWorkDict.put("物联网工程","技术人员/工程师");
        mapWorkDict.put("企业管理","企业白领");
        mapWorkDict.put("自己事业","企业家");
        mapWorkDict.put("土木工程","技术人员/工程师");
        mapWorkDict.put("飞行技术","技术人员/工程师");
        mapWorkDict.put("建筑工程","技术人员/工程师");
        mapWorkDict.put("通信行业","技术人员/工程师");
        mapWorkDict.put("幼儿教师","老师");
        mapWorkDict.put("文职","企业白领");
        mapWorkDict.put("前端开发","技术人员/工程师");
        mapWorkDict.put("科技电子行业","技术人员/工程师");
        mapWorkDict.put("一般公司","企业白领");
        mapWorkDict.put("工程师","技术人员/工程师");
        mapWorkDict.put("电力工人","技术人员/工程师");
        mapWorkDict.put("技术职业","技术人员/工程师");
        mapWorkDict.put("程序员","程序员");
        mapWorkDict.put("物联网","技术人员/工程师");
        mapWorkDict.put("办公室人员","企业白领");
        mapWorkDict.put("科技","技术人员/工程师");
        mapWorkDict.put("项目经理","企业白领");
        mapWorkDict.put("空间设计","技术人员/工程师");
        mapWorkDict.put("公司上班","企业白领");
        mapWorkDict.put("事业员","企业白领");
        mapWorkDict.put("业务员","企业白领");
        mapWorkDict.put("经理","企业白领");
        mapWorkDict.put("医疗","医生");
        mapWorkDict.put("党政机关、事业单位","政府公务员");
        mapWorkDict.put("计算机软件","技术人员/工程师");
        mapWorkDict.put("电网","技术人员/工程师");
        mapWorkDict.put("土建工程师","技术人员/工程师");
        mapWorkDict.put("专业技术","技术人员/工程师");
        mapWorkDict.put("工程行业","技术人员/工程师");
        mapWorkDict.put("人工智能","技术人员/工程师");
        mapWorkDict.put("互联网软件","技术人员/工程师");
        mapWorkDict.put("电力工程", "技术人员/工程师");
        mapWorkDict.put("小学教育","老师");
        mapWorkDict.put("私企","企业白领");
        mapWorkDict.put("工业互联网","技术人员/工程师");
        mapWorkDict.put("技术","技术人员/工程师");
        mapWorkDict.put("工程造价","技术人员/工程师");
        mapWorkDict.put("办公","企业白领");
        mapWorkDict.put("公安","政府公务员");
        mapWorkDict.put("培训讲师","老师");
        mapWorkDict.put("城建","技术人员/工程师");
        mapWorkDict.put("技术人员","技术人员/工程师");
        mapWorkDict.put("监理工程师","技术人员/工程师");
        mapWorkDict.put("IT服务","技术人员/工程师");
        mapWorkDict.put("企业家","企业家");
        mapWorkDict.put("企业老板","企业家");
        mapWorkDict.put("软件工程师","技术人员/工程师");
        mapWorkDict.put("金融科技","企业白领");
        mapWorkDict.put("质量检测","技术人员/工程师");
    }


}
